name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pull-request-check:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore source/

      - name: Build and analyze
        shell: pwsh
        run: |
          dotnet build --configuration Release --no-restore source/
          dotnet test source/
